version: '3.8'
services:
  mongo-test:
    image: mongo:7.0-jammy
    ports:
      - "27010:27017"
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin1
      MONGO_INITDB_ROOT_PASSWORD: root